"""
Analysis models for Phase 2: AI Reasoning Layer.

This module defines enriched data structures that combine Phase 1 failure
detection with actual source code context for AI-powered root cause analysis.
"""

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field

from ci_failure_analyzer.models.log_models import FailureContext


class RootCauseBucket(str, Enum):
    """Classification categories for failure root causes."""
    
    LOGIC_ERROR = "LOGIC_ERROR"
    ENVIRONMENT_FAILURE = "ENVIRONMENT_FAILURE"
    TEST_FLAKINESS = "TEST_FLAKINESS"
    INFRA_ISSUE = "INFRA_ISSUE"
    UNKNOWN = "UNKNOWN"


class CodeSnippet(BaseModel):
    """
    Represents a surgical code extraction from a source file.
    
    Attributes:
        file_path: Relative path to the source file
        start_line: First line number in the snippet (1-indexed)
        end_line: Last line number in the snippet (1-indexed)
        content: The actual code lines with line numbers
        error_line: The specific line where the error occurred
    """
    
    file_path: str = Field(
        ...,
        description="Relative path to the source file"
    )
    start_line: int = Field(
        ...,
        description="Starting line number (1-indexed)",
        ge=1
    )
    end_line: int = Field(
        ...,
        description="Ending line number (1-indexed)",
        ge=1
    )
    content: str = Field(
        ...,
        description="Code content with line numbers"
    )
    error_line: Optional[int] = Field(
        default=None,
        description="The specific line where error occurred"
    )


class EnrichedFailureContext(BaseModel):
    """
    Extended failure context with source code evidence.
    
    This combines the Phase 1 FailureContext (log-based detection) with
    actual source code snippets to enable evidence-based AI analysis.
    
    Attributes:
        original_failure: The Phase 1 failure detection result
        code_snippet: Surgical extraction of code around the error
        test_snippet: The actual test case code
        missing_files: List of files that could not be located
        resolution_notes: Human-readable notes about file resolution
    """
    
    original_failure: FailureContext = Field(
        ...,
        description="Original failure context from Phase 1"
    )
    code_snippet: Optional[CodeSnippet] = Field(
        default=None,
        description="Source code context around the error"
    )
    test_snippet: Optional[CodeSnippet] = Field(
        default=None,
        description="Test case source code"
    )
    missing_files: List[str] = Field(
        default_factory=list,
        description="Files that could not be located in local repository"
    )
    resolution_notes: List[str] = Field(
        default_factory=list,
        description="Notes about path resolution and file discovery"
    )
    
    @property
    def has_code_context(self) -> bool:
        """Check if code context is available."""
        return self.code_snippet is not None
    
    @property
    def has_test_context(self) -> bool:
        """Check if test context is available."""
        return self.test_snippet is not None
    
    @property
    def context_completeness_score(self) -> float:
        """
        Calculate how much context is available (0.0 to 1.0).
        
        Returns:
            0.0 = No context available
            0.5 = Either code or test available
            1.0 = Both code and test available
        """
        score = 0.0
        if self.has_code_context:
            score += 0.5
        if self.has_test_context:
            score += 0.5
        return score


class RCAReport(BaseModel):
    """
    Root Cause Analysis report generated by AI reasoning.
    
    Attributes:
        failure_id: Unique identifier linking back to original failure
        root_cause_bucket: Classification category
        root_cause_summary: Concise non-technical overview
        technical_analysis: Detailed forensic breakdown
        suggested_fix: Specific recommendation for remediation
        confidence_score: AI certainty level (0.0 to 1.0)
        evidence: Supporting evidence used in analysis
    """
    
    failure_id: str = Field(
        ...,
        description="Unique identifier for this failure"
    )
    root_cause_bucket: RootCauseBucket = Field(
        ...,
        description="Classification of the root cause"
    )
    root_cause_summary: str = Field(
        ...,
        description="One-sentence summary for stakeholders",
        min_length=10
    )
    technical_analysis: str = Field(
        ...,
        description="Detailed forensic analysis with code references",
        min_length=50
    )
    suggested_fix: str = Field(
        ...,
        description="Concrete remediation recommendation",
        min_length=10
    )
    confidence_score: float = Field(
        ...,
        description="Confidence level based on available context",
        ge=0.0,
        le=1.0
    )
    evidence: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Supporting evidence: log clues, code files, missing context"
    )
